# Generated by Django 3.0.4 on 2020-03-30 19:56

import Apps.Usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_auto_20200327_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'verbose_name': 'Cancion', 'verbose_name_plural': 'Canciones'},
        ),
        migrations.AlterModelOptions(
            name='playlistcanciones',
            options={'verbose_name': 'PlaylistCanciones', 'verbose_name_plural': 'PlaylistCanciones'},
        ),
        migrations.AlterModelOptions(
            name='usuariocanciones',
            options={'verbose_name': 'UsuarioCanciones', 'verbose_name_plural': 'UsuariosCanciones'},
        ),
        migrations.AlterField(
            model_name='album',
            name='duracion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='foto',
            field=models.ImageField(blank=True, upload_to=Apps.Usuarios.models.images_path),
        ),
        migrations.AlterField(
            model_name='disquera',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
