# Generated by Django 3.0.4 on 2020-03-30 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0005_auto_20200330_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='disquera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Disquera'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Genero'),
            preserve_default=False,
        ),
    ]
